<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class AddFiftyTeachingStaffSeeder extends Seeder
{
    public function run(): void
    {
        $teachingStaff = [
            [
                'employee_code' => 'EMP-136',
                'first_name'    => 'Arvind',
                'last_name'     => 'Swaminathan',
                'gender'        => 'male',
                'dob'           => '1982-04-12',
                'mobile'        => '9840123451',
                'personal_email'=> 'arvind.swami82@gmail.com',
                'official_email'=> 'arvind.swaminathan@schoolerp.in',
                'residential_address' => '42, Temple View Avenue, Gandhi Nagar, Chennai, Tamil Nadu - 600020',
                'department'    => 'Science',
                'designation'   => 'Chemistry HOD',
                'qualification' => 'M.Sc., Ph.D. Chemistry, B.Ed.',
                'joining_date'  => '2018-05-10',
                'basic_salary'  => 68000,
            ],
            [
                'employee_code' => 'EMP-137',
                'first_name'    => 'Meenakshi',
                'last_name'     => 'Sundaram',
                'gender'        => 'female',
                'dob'           => '1986-08-25',
                'mobile'        => '9840123452',
                'personal_email'=> 'meenakshi.sundaram@gmail.com',
                'official_email'=> 'meenakshi.sundaram@schoolerp.in',
                'residential_address' => '15/3, Lake View Street, Velachery, Chennai, Tamil Nadu - 600042',
                'department'    => 'Mathematics',
                'designation'   => 'PGT Mathematics',
                'qualification' => 'M.Sc. Applied Maths, B.Ed.',
                'joining_date'  => '2019-06-15',
                'basic_salary'  => 58000,
            ],
            [
                'employee_code' => 'EMP-138',
                'first_name'    => 'Karthik',
                'last_name'     => 'Radhakrishnan',
                'gender'        => 'male',
                'dob'           => '1988-11-14',
                'mobile'        => '9840123453',
                'personal_email'=> 'karthik.radha88@gmail.com',
                'official_email'=> 'karthik.radhakrishnan@schoolerp.in',
                'residential_address' => '88, Anna Nagar West, Madurai, Tamil Nadu - 625020',
                'department'    => 'Science',
                'designation'   => 'Senior Physics Faculty',
                'qualification' => 'M.Sc. Physics, M.Phil, B.Ed.',
                'joining_date'  => '2020-01-20',
                'basic_salary'  => 56000,
            ],
            [
                'employee_code' => 'EMP-139',
                'first_name'    => 'Ananya',
                'last_name'     => 'Sengupta',
                'gender'        => 'female',
                'dob'           => '1990-03-19',
                'mobile'        => '9840123454',
                'personal_email'=> 'ananya.sengupta90@gmail.com',
                'official_email'=> 'ananya.sengupta@schoolerp.in',
                'residential_address' => '7B, Green Park Extension, New Delhi - 110016',
                'department'    => 'English',
                'designation'   => 'PGT English & Literature',
                'qualification' => 'M.A. English, M.Ed.',
                'joining_date'  => '2020-07-01',
                'basic_salary'  => 54000,
            ],
            [
                'employee_code' => 'EMP-140',
                'first_name'    => 'Venkatesh',
                'last_name'     => 'Iyer',
                'gender'        => 'male',
                'dob'           => '1985-09-30',
                'mobile'        => '9840123455',
                'personal_email'=> 'venkatesh.iyer85@gmail.com',
                'official_email'=> 'venkatesh.iyer@schoolerp.in',
                'residential_address' => '104, IT Corridor Enclave, Thoraipakkam, Chennai, Tamil Nadu - 600097',
                'department'    => 'Computer Science',
                'designation'   => 'Computer Science & AI Specialist',
                'qualification' => 'M.Tech IT, B.Ed.',
                'joining_date'  => '2019-11-15',
                'basic_salary'  => 62000,
            ],
            [
                'employee_code' => 'EMP-141',
                'first_name'    => 'Deepa',
                'last_name'     => 'Raghavan',
                'gender'        => 'female',
                'dob'           => '1989-12-05',
                'mobile'        => '9840123456',
                'personal_email'=> 'deepa.raghavan89@gmail.com',
                'official_email'=> 'deepa.raghavan@schoolerp.in',
                'residential_address' => '22, Royal Palms, Race Course Road, Coimbatore, Tamil Nadu - 641018',
                'department'    => 'Science',
                'designation'   => 'Senior Biology Teacher',
                'qualification' => 'M.Sc. Botany & Biotechnology, B.Ed.',
                'joining_date'  => '2021-03-10',
                'basic_salary'  => 55000,
            ],
            [
                'employee_code' => 'EMP-142',
                'first_name'    => 'Balasubramanian',
                'last_name'     => 'Natarajan',
                'gender'        => 'male',
                'dob'           => '1979-02-18',
                'mobile'        => '9840123457',
                'personal_email'=> 'bala.natarajan79@gmail.com',
                'official_email'=> 'balasubramanian.natarajan@schoolerp.in',
                'residential_address' => '12, Car Street, Triplicane, Chennai, Tamil Nadu - 600005',
                'department'    => 'Tamil',
                'designation'   => 'Tamil Language HOD',
                'qualification' => 'M.A. Tamil, Ph.D., NET',
                'joining_date'  => '2017-06-01',
                'basic_salary'  => 60000,
            ],
            [
                'employee_code' => 'EMP-143',
                'first_name'    => 'Sunita',
                'last_name'     => 'Mukherjee',
                'gender'        => 'female',
                'dob'           => '1987-05-14',
                'mobile'        => '9840123458',
                'personal_email'=> 'sunita.mukh87@gmail.com',
                'official_email'=> 'sunita.mukherjee@schoolerp.in',
                'residential_address' => '54, Salt Lake Sector 2, Kolkata, West Bengal - 700091',
                'department'    => 'Commerce',
                'designation'   => 'PGT Economics & Statistics',
                'qualification' => 'M.A. Economics, B.Ed.',
                'joining_date'  => '2020-08-15',
                'basic_salary'  => 57000,
            ],
            [
                'employee_code' => 'EMP-144',
                'first_name'    => 'Manoj',
                'last_name'     => 'Prabhakar',
                'gender'        => 'male',
                'dob'           => '1988-07-22',
                'mobile'        => '9840123459',
                'personal_email'=> 'manoj.prabhakar88@gmail.com',
                'official_email'=> 'manoj.prabhakar@schoolerp.in',
                'residential_address' => '31, Sports Complex Road, Trichy, Tamil Nadu - 620001',
                'department'    => 'Physical Education',
                'designation'   => 'Physical Education Director',
                'qualification' => 'M.P.Ed., NIS Certified Athletics Coach',
                'joining_date'  => '2019-04-10',
                'basic_salary'  => 52000,
            ],
            [
                'employee_code' => 'EMP-145',
                'first_name'    => 'Sneha',
                'last_name'     => 'Kulkarni',
                'gender'        => 'female',
                'dob'           => '1992-10-11',
                'mobile'        => '9840123460',
                'personal_email'=> 'sneha.kulkarni92@gmail.com',
                'official_email'=> 'sneha.kulkarni@schoolerp.in',
                'residential_address' => '78, Shivaji Nagar, Pune, Maharashtra - 411005',
                'department'    => 'Social Studies',
                'designation'   => 'TGT Social Science',
                'qualification' => 'M.A. History, B.Ed.',
                'joining_date'  => '2021-06-01',
                'basic_salary'  => 48000,
            ],
            [
                'employee_code' => 'EMP-146',
                'first_name'    => 'Ranganathan',
                'last_name'     => 'Srinivasan',
                'gender'        => 'male',
                'dob'           => '1981-01-29',
                'mobile'        => '9840123461',
                'personal_email'=> 'ranga.srini81@gmail.com',
                'official_email'=> 'ranganathan.srinivasan@schoolerp.in',
                'residential_address' => '9, T. Nagar North Usman Road, Chennai, Tamil Nadu - 600017',
                'department'    => 'Commerce',
                'designation'   => 'PGT Accountancy & Commerce',
                'qualification' => 'M.Com, FCA, B.Ed.',
                'joining_date'  => '2018-09-01',
                'basic_salary'  => 64000,
            ],
            [
                'employee_code' => 'EMP-147',
                'first_name'    => 'Kavitha',
                'last_name'     => 'Krishnan',
                'gender'        => 'female',
                'dob'           => '1991-04-16',
                'mobile'        => '9840123462',
                'personal_email'=> 'kavitha.krishnan91@gmail.com',
                'official_email'=> 'kavitha.krishnan@schoolerp.in',
                'residential_address' => '33, K.K. Nagar, Madurai, Tamil Nadu - 625020',
                'department'    => 'Science',
                'designation'   => 'Senior Chemistry Teacher',
                'qualification' => 'M.Sc. Organic Chemistry, B.Ed.',
                'joining_date'  => '2021-02-15',
                'basic_salary'  => 53000,
            ],
            [
                'employee_code' => 'EMP-148',
                'first_name'    => 'Suresh',
                'last_name'     => 'Narayanan',
                'gender'        => 'male',
                'dob'           => '1993-06-08',
                'mobile'        => '9840123463',
                'personal_email'=> 'suresh.narayanan93@gmail.com',
                'official_email'=> 'suresh.narayanan@schoolerp.in',
                'residential_address' => '19, R.S. Puram, Coimbatore, Tamil Nadu - 641002',
                'department'    => 'Mathematics',
                'designation'   => 'TGT Mathematics',
                'qualification' => 'M.Sc. Mathematics, B.Ed.',
                'joining_date'  => '2021-09-01',
                'basic_salary'  => 49000,
            ],
            [
                'employee_code' => 'EMP-149',
                'first_name'    => 'Radhika',
                'last_name'     => 'Menachery',
                'gender'        => 'female',
                'dob'           => '1987-11-23',
                'mobile'        => '9840123464',
                'personal_email'=> 'radhika.menon87@gmail.com',
                'official_email'=> 'radhika.menachery@schoolerp.in',
                'residential_address' => '44, Panampilly Nagar, Kochi, Kerala - 682036',
                'department'    => 'Science',
                'designation'   => 'PGT Zoology & Life Sciences',
                'qualification' => 'M.Sc. Zoology, B.Ed.',
                'joining_date'  => '2020-10-15',
                'basic_salary'  => 54000,
            ],
            [
                'employee_code' => 'EMP-150',
                'first_name'    => 'Amitava',
                'last_name'     => 'Das',
                'gender'        => 'male',
                'dob'           => '1989-09-12',
                'mobile'        => '9840123465',
                'personal_email'=> 'amitava.das89@gmail.com',
                'official_email'=> 'amitava.das@schoolerp.in',
                'residential_address' => '62, Gariahat Road, South Kolkata, West Bengal - 700019',
                'department'    => 'Social Studies',
                'designation'   => 'Senior Geography Faculty',
                'qualification' => 'M.Sc. Geography, GIS Diploma, B.Ed.',
                'joining_date'  => '2021-01-10',
                'basic_salary'  => 51000,
            ],
            [
                'employee_code' => 'EMP-151',
                'first_name'    => 'Shalini',
                'last_name'     => 'Pillai',
                'gender'        => 'female',
                'dob'           => '1994-02-17',
                'mobile'        => '9840123466',
                'personal_email'=> 'shalini.pillai94@gmail.com',
                'official_email'=> 'shalini.pillai@schoolerp.in',
                'residential_address' => '17, Shastri Nagar, Adyar, Chennai, Tamil Nadu - 600020',
                'department'    => 'Hindi',
                'designation'   => 'Hindi Language Specialist',
                'qualification' => 'M.A. Hindi, B.Ed.',
                'joining_date'  => '2022-03-01',
                'basic_salary'  => 47000,
            ],
            [
                'employee_code' => 'EMP-152',
                'first_name'    => 'Vijay',
                'last_name'     => 'Anand',
                'gender'        => 'male',
                'dob'           => '1986-12-03',
                'mobile'        => '9840123467',
                'personal_email'=> 'vijay.anand86@gmail.com',
                'official_email'=> 'vijay.anand@schoolerp.in',
                'residential_address' => '5B, Silicon Heights, Electronic City, Bangalore, Karnataka - 560100',
                'department'    => 'Computer Science',
                'designation'   => 'Robotics & STEM Lab Incharge',
                'qualification' => 'B.E. Robotics & AI, B.Ed.',
                'joining_date'  => '2020-12-01',
                'basic_salary'  => 58000,
            ],
            [
                'employee_code' => 'EMP-153',
                'first_name'    => 'Poornima',
                'last_name'     => 'Rajagopal',
                'gender'        => 'female',
                'dob'           => '1984-06-28',
                'mobile'        => '9840123468',
                'personal_email'=> 'poornima.raja84@gmail.com',
                'official_email'=> 'poornima.rajagopal@schoolerp.in',
                'residential_address' => '28, South Mada Street, Mylapore, Chennai, Tamil Nadu - 600004',
                'department'    => 'Sanskrit',
                'designation'   => 'Sanskrit Language Faculty',
                'qualification' => 'M.A. Sanskrit Sahitya, B.Ed.',
                'joining_date'  => '2019-07-20',
                'basic_salary'  => 50000,
            ],
            [
                'employee_code' => 'EMP-154',
                'first_name'    => 'Harish',
                'last_name'     => 'Chander',
                'gender'        => 'male',
                'dob'           => '1993-01-15',
                'mobile'        => '9840123469',
                'personal_email'=> 'harish.chander93@gmail.com',
                'official_email'=> 'harish.chander@schoolerp.in',
                'residential_address' => '74, Model Town, Jalandhar, Punjab - 144003',
                'department'    => 'Science',
                'designation'   => 'TGT Physics',
                'qualification' => 'M.Sc. Applied Physics, B.Ed.',
                'joining_date'  => '2022-05-15',
                'basic_salary'  => 48000,
            ],
            [
                'employee_code' => 'EMP-155',
                'first_name'    => 'Gayatri',
                'last_name'     => 'Ramaswamy',
                'gender'        => 'female',
                'dob'           => '1983-09-04',
                'mobile'        => '9840123470',
                'personal_email'=> 'gayatri.rama83@gmail.com',
                'official_email'=> 'gayatri.ramaswamy@schoolerp.in',
                'residential_address' => '102, Besant Nagar Beach Road, Chennai, Tamil Nadu - 600090',
                'department'    => 'Primary Education',
                'designation'   => 'PRT Primary Head & Coordinator',
                'qualification' => 'M.A. Psychology, B.Ed., NTT',
                'joining_date'  => '2018-06-10',
                'basic_salary'  => 52000,
            ],
            [
                'employee_code' => 'EMP-156',
                'first_name'    => 'Chetan',
                'last_name'     => 'Deshmukh',
                'gender'        => 'male',
                'dob'           => '1987-10-09',
                'mobile'        => '9840123471',
                'personal_email'=> 'chetan.deshmukh87@gmail.com',
                'official_email'=> 'chetan.deshmukh@schoolerp.in',
                'residential_address' => '25, Ramdas Peth, Nagpur, Maharashtra - 440010',
                'department'    => 'Social Studies',
                'designation'   => 'PGT Political Science & Civics',
                'qualification' => 'M.A. Political Science, B.Ed.',
                'joining_date'  => '2021-07-15',
                'basic_salary'  => 51000,
            ],
            [
                'employee_code' => 'EMP-157',
                'first_name'    => 'Divya',
                'last_name'     => 'Mohan',
                'gender'        => 'female',
                'dob'           => '1992-03-31',
                'mobile'        => '9840123472',
                'personal_email'=> 'divya.mohan92@gmail.com',
                'official_email'=> 'divya.mohan@schoolerp.in',
                'residential_address' => '67, Artists Colony, Injambakkam, ECR, Chennai - 600115',
                'department'    => 'Fine Arts',
                'designation'   => 'Fine Arts & Visual Design Master',
                'qualification' => 'M.F.A. Painting & Applied Arts',
                'joining_date'  => '2020-04-01',
                'basic_salary'  => 49000,
            ],
            [
                'employee_code' => 'EMP-158',
                'first_name'    => 'Senthil',
                'last_name'     => 'Kumar',
                'gender'        => 'male',
                'dob'           => '1985-04-20',
                'mobile'        => '9840123473',
                'personal_email'=> 'senthil.kumar85@gmail.com',
                'official_email'=> 'senthil.kumar@schoolerp.in',
                'residential_address' => '14, Thillai Nagar 5th Cross, Trichy, Tamil Nadu - 620018',
                'department'    => 'Tamil',
                'designation'   => 'Senior Tamil Lecturer',
                'qualification' => 'M.A. Tamil Literature, M.Phil, B.Ed.',
                'joining_date'  => '2019-08-10',
                'basic_salary'  => 53000,
            ],
            [
                'employee_code' => 'EMP-159',
                'first_name'    => 'Archana',
                'last_name'     => 'Bhat',
                'gender'        => 'female',
                'dob'           => '1993-07-14',
                'mobile'        => '9840123474',
                'personal_email'=> 'archana.bhat93@gmail.com',
                'official_email'=> 'archana.bhat@schoolerp.in',
                'residential_address' => '89, Malleshwaram 15th Cross, Bangalore, Karnataka - 560003',
                'department'    => 'English',
                'designation'   => 'TGT English',
                'qualification' => 'M.A. English, B.Ed., CELTA',
                'joining_date'  => '2022-01-15',
                'basic_salary'  => 47000,
            ],
            [
                'employee_code' => 'EMP-160',
                'first_name'    => 'Naveen',
                'last_name'     => 'Patnaik',
                'gender'        => 'male',
                'dob'           => '1991-08-05',
                'mobile'        => '9840123475',
                'personal_email'=> 'naveen.patnaik91@gmail.com',
                'official_email'=> 'naveen.patnaik@schoolerp.in',
                'residential_address' => '38, Saheed Nagar, Bhubaneswar, Odisha - 751007',
                'department'    => 'Music',
                'designation'   => 'Music & Performing Arts Teacher',
                'qualification' => 'M.Music (Vocal & Keyboard)',
                'joining_date'  => '2021-11-01',
                'basic_salary'  => 46000,
            ],
            [
                'employee_code' => 'EMP-161',
                'first_name'    => 'Lavanya',
                'last_name'     => 'Subramaniam',
                'gender'        => 'female',
                'dob'           => '1990-11-19',
                'mobile'        => '9840123476',
                'personal_email'=> 'lavanya.subra90@gmail.com',
                'official_email'=> 'lavanya.subramaniam@schoolerp.in',
                'residential_address' => '51, Sai Baba Colony, Coimbatore, Tamil Nadu - 641011',
                'department'    => 'Science',
                'designation'   => 'Environmental Science Faculty',
                'qualification' => 'M.Sc. Environmental Science, B.Ed.',
                'joining_date'  => '2021-04-20',
                'basic_salary'  => 50000,
            ],
            [
                'employee_code' => 'EMP-162',
                'first_name'    => 'Pradeep',
                'last_name'     => 'Kothari',
                'gender'        => 'male',
                'dob'           => '1984-01-18',
                'mobile'        => '9840123477',
                'personal_email'=> 'pradeep.kothari84@gmail.com',
                'official_email'=> 'pradeep.kothari@schoolerp.in',
                'residential_address' => '108, C.G. Road, Navrangpura, Ahmedabad, Gujarat - 380009',
                'department'    => 'Commerce',
                'designation'   => 'Senior Business Studies Teacher',
                'qualification' => 'M.Com, MBA Finance, B.Ed.',
                'joining_date'  => '2019-03-15',
                'basic_salary'  => 59000,
            ],
            [
                'employee_code' => 'EMP-163',
                'first_name'    => 'Geetha',
                'last_name'     => 'Varadarajan',
                'gender'        => 'female',
                'dob'           => '1988-02-27',
                'mobile'        => '9840123478',
                'personal_email'=> 'geetha.varada88@gmail.com',
                'official_email'=> 'geetha.varadarajan@schoolerp.in',
                'residential_address' => '71, Alwarpet High Road, Chennai, Tamil Nadu - 600018',
                'department'    => 'Mathematics',
                'designation'   => 'PGT Pure Mathematics',
                'qualification' => 'M.Sc. Statistics & Maths, B.Ed.',
                'joining_date'  => '2020-06-01',
                'basic_salary'  => 56000,
            ],
            [
                'employee_code' => 'EMP-164',
                'first_name'    => 'Alok Nath',
                'last_name'     => 'Tripathy',
                'gender'        => 'male',
                'dob'           => '1992-05-09',
                'mobile'        => '9840123479',
                'personal_email'=> 'alok.tripathy92@gmail.com',
                'official_email'=> 'alok.tripathy@schoolerp.in',
                'residential_address' => '29, Civil Lines, Prayagraj, Uttar Pradesh - 211001',
                'department'    => 'Science',
                'designation'   => 'TGT General Science',
                'qualification' => 'M.Sc. Chemistry, B.Ed.',
                'joining_date'  => '2022-08-01',
                'basic_salary'  => 46000,
            ],
            [
                'employee_code' => 'EMP-165',
                'first_name'    => 'Vani',
                'last_name'     => 'Chandrasekhar',
                'gender'        => 'female',
                'dob'           => '1989-10-24',
                'mobile'        => '9840123480',
                'personal_email'=> 'vani.chandra89@gmail.com',
                'official_email'=> 'vani.chandrasekhar@schoolerp.in',
                'residential_address' => '12A, Whitefield Palms, Bangalore, Karnataka - 560066',
                'department'    => 'Languages',
                'designation'   => 'French & Foreign Language Teacher',
                'qualification' => 'M.A. French, DELF B2 Certified',
                'joining_date'  => '2021-05-10',
                'basic_salary'  => 55000,
            ],
            [
                'employee_code' => 'EMP-166',
                'first_name'    => 'Muralidharan',
                'last_name'     => 'Namboodiri',
                'gender'        => 'male',
                'dob'           => '1987-03-12',
                'mobile'        => '9840123481',
                'personal_email'=> 'murali.namboothiri87@gmail.com',
                'official_email'=> 'muralidharan.namboodiri@schoolerp.in',
                'residential_address' => '5, Temple Gate, Guruvayur, Thrissur, Kerala - 680101',
                'department'    => 'Physical Education',
                'designation'   => 'Yoga & Wellness Instructor',
                'qualification' => 'M.Sc. Yoga & Physical Wellness, PG Diploma',
                'joining_date'  => '2020-02-15',
                'basic_salary'  => 48000,
            ],
            [
                'employee_code' => 'EMP-167',
                'first_name'    => 'Rekha',
                'last_name'     => 'Jha',
                'gender'        => 'female',
                'dob'           => '1986-12-19',
                'mobile'        => '9840123482',
                'personal_email'=> 'rekha.jha86@gmail.com',
                'official_email'=> 'rekha.jha@schoolerp.in',
                'residential_address' => '45, Kankarbagh Main Road, Patna, Bihar - 800020',
                'department'    => 'Hindi',
                'designation'   => 'Senior Hindi Faculty',
                'qualification' => 'M.A. Hindi Literature, M.Ed.',
                'joining_date'  => '2019-10-01',
                'basic_salary'  => 51000,
            ],
            [
                'employee_code' => 'EMP-168',
                'first_name'    => 'Dinesh',
                'last_name'     => 'Thangavel',
                'gender'        => 'male',
                'dob'           => '1994-06-11',
                'mobile'        => '9840123483',
                'personal_email'=> 'dinesh.thangavel94@gmail.com',
                'official_email'=> 'dinesh.thangavel@schoolerp.in',
                'residential_address' => '82, Salem Main Road, Erode, Tamil Nadu - 638001',
                'department'    => 'Computer Science',
                'designation'   => 'TGT Computer Applications',
                'qualification' => 'M.C.A., B.Ed.',
                'joining_date'  => '2022-02-01',
                'basic_salary'  => 49000,
            ],
            [
                'employee_code' => 'EMP-169',
                'first_name'    => 'Shilpa',
                'last_name'     => 'Hegde',
                'gender'        => 'female',
                'dob'           => '1995-09-02',
                'mobile'        => '9840123484',
                'personal_email'=> 'shilpa.hegde95@gmail.com',
                'official_email'=> 'shilpa.hegde@schoolerp.in',
                'residential_address' => '23, Kadri Temple Road, Mangalore, Karnataka - 575002',
                'department'    => 'Primary Education',
                'designation'   => 'PRT Mathematics',
                'qualification' => 'B.Sc. Mathematics, B.Ed.',
                'joining_date'  => '2022-06-15',
                'basic_salary'  => 44000,
            ],
            [
                'employee_code' => 'EMP-170',
                'first_name'    => 'Anand',
                'last_name'     => 'Vardhan',
                'gender'        => 'male',
                'dob'           => '1987-04-15',
                'mobile'        => '9840123485',
                'personal_email'=> 'anand.vardhan87@gmail.com',
                'official_email'=> 'anand.vardhan@schoolerp.in',
                'residential_address' => '19, Hazratganj, Lucknow, Uttar Pradesh - 226001',
                'department'    => 'Social Studies',
                'designation'   => 'PGT History & World Civilizations',
                'qualification' => 'M.A. Modern History, NET, B.Ed.',
                'joining_date'  => '2020-09-01',
                'basic_salary'  => 53000,
            ],
            [
                'employee_code' => 'EMP-171',
                'first_name'    => 'Meera',
                'last_name'     => 'Madhavan',
                'gender'        => 'female',
                'dob'           => '1992-01-26',
                'mobile'        => '9840123486',
                'personal_email'=> 'meera.madhavan92@gmail.com',
                'official_email'=> 'meera.madhavan@schoolerp.in',
                'residential_address' => '39, Jawahar Nagar, Kowdiar, Thiruvananthapuram, Kerala - 695003',
                'department'    => 'English',
                'designation'   => 'TGT English & Communication',
                'qualification' => 'M.A. Linguistics, B.Ed.',
                'joining_date'  => '2021-12-01',
                'basic_salary'  => 48000,
            ],
            [
                'employee_code' => 'EMP-172',
                'first_name'    => 'Girish',
                'last_name'     => 'Bapat',
                'gender'        => 'male',
                'dob'           => '1990-08-17',
                'mobile'        => '9840123487',
                'personal_email'=> 'girish.bapat90@gmail.com',
                'official_email'=> 'girish.bapat@schoolerp.in',
                'residential_address' => '64, Kothrud Main Road, Pune, Maharashtra - 411038',
                'department'    => 'Physical Education',
                'designation'   => 'Physical Education & Athletics Coach',
                'qualification' => 'B.P.Ed., State Athletics Coach',
                'joining_date'  => '2021-07-01',
                'basic_salary'  => 46000,
            ],
            [
                'employee_code' => 'EMP-173',
                'first_name'    => 'Swati',
                'last_name'     => 'Srivastava',
                'gender'        => 'female',
                'dob'           => '1989-07-07',
                'mobile'        => '9840123488',
                'personal_email'=> 'swati.sri89@gmail.com',
                'official_email'=> 'swati.srivastava@schoolerp.in',
                'residential_address' => '11, Gomti Nagar, Lucknow, Uttar Pradesh - 226010',
                'department'    => 'Science',
                'designation'   => 'PGT Applied Chemistry',
                'qualification' => 'M.Sc. Analytical Chemistry, B.Ed.',
                'joining_date'  => '2021-03-20',
                'basic_salary'  => 52000,
            ],
            [
                'employee_code' => 'EMP-174',
                'first_name'    => 'Balaji',
                'last_name'     => 'Soundararajan',
                'gender'        => 'male',
                'dob'           => '1983-11-13',
                'mobile'        => '9840123489',
                'personal_email'=> 'balaji.soundar83@gmail.com',
                'official_email'=> 'balaji.soundararajan@schoolerp.in',
                'residential_address' => '56, Sastri Nagar, Chromepet, Chennai, Tamil Nadu - 600044',
                'department'    => 'Mathematics',
                'designation'   => 'Senior Mathematics Mentor',
                'qualification' => 'M.Sc. Mathematics, M.Phil, B.Ed.',
                'joining_date'  => '2019-01-10',
                'basic_salary'  => 57000,
            ],
            [
                'employee_code' => 'EMP-175',
                'first_name'    => 'Aparna',
                'last_name'     => 'Nair',
                'gender'        => 'female',
                'dob'           => '1996-04-18',
                'mobile'        => '9840123490',
                'personal_email'=> 'aparna.nair96@gmail.com',
                'official_email'=> 'aparna.nair@schoolerp.in',
                'residential_address' => '18, Marine Drive, Kochi, Kerala - 682031',
                'department'    => 'Primary Education',
                'designation'   => 'PRT Science & Nature Studies',
                'qualification' => 'B.Sc. Life Sciences, B.Ed.',
                'joining_date'  => '2023-01-15',
                'basic_salary'  => 43000,
            ],
            [
                'employee_code' => 'EMP-176',
                'first_name'    => 'Hemant',
                'last_name'     => 'Joshi',
                'gender'        => 'male',
                'dob'           => '1988-05-21',
                'mobile'        => '9840123491',
                'personal_email'=> 'hemant.joshi88@gmail.com',
                'official_email'=> 'hemant.joshi@schoolerp.in',
                'residential_address' => '37, Vastrapur Lake Avenue, Ahmedabad, Gujarat - 380015',
                'department'    => 'Computer Science',
                'designation'   => 'Computer Hardware & Networking Faculty',
                'qualification' => 'B.Tech CSE, Cisco Certified, B.Ed.',
                'joining_date'  => '2021-10-15',
                'basic_salary'  => 51000,
            ],
            [
                'employee_code' => 'EMP-177',
                'first_name'    => 'Usha',
                'last_name'     => 'Padmanabhan',
                'gender'        => 'female',
                'dob'           => '1987-03-08',
                'mobile'        => '9840123492',
                'personal_email'=> 'usha.padma87@gmail.com',
                'official_email'=> 'usha.padmanabhan@schoolerp.in',
                'residential_address' => '26, Ramanuja Nagar, Thanjavur, Tamil Nadu - 613004',
                'department'    => 'Tamil',
                'designation'   => 'Senior Tamil Teacher',
                'qualification' => 'M.A. Tamil, B.Ed.',
                'joining_date'  => '2020-05-10',
                'basic_salary'  => 50000,
            ],
            [
                'employee_code' => 'EMP-178',
                'first_name'    => 'Saurabh',
                'last_name'     => 'Ganguly',
                'gender'        => 'male',
                'dob'           => '1993-12-14',
                'mobile'        => '9840123493',
                'personal_email'=> 'saurabh.ganguly93@gmail.com',
                'official_email'=> 'saurabh.ganguly@schoolerp.in',
                'residential_address' => '93, Ballygunge Circular Road, Kolkata, West Bengal - 700019',
                'department'    => 'Social Studies',
                'designation'   => 'TGT Social Sciences',
                'qualification' => 'M.A. Sociology & Geography, B.Ed.',
                'joining_date'  => '2022-07-20',
                'basic_salary'  => 47000,
            ],
            [
                'employee_code' => 'EMP-179',
                'first_name'    => 'Nandini',
                'last_name'     => 'Kalyan',
                'gender'        => 'female',
                'dob'           => '1991-09-17',
                'mobile'        => '9840123494',
                'personal_email'=> 'nandini.kalyan91@gmail.com',
                'official_email'=> 'nandini.kalyan@schoolerp.in',
                'residential_address' => '40, Kalakshetra Colony, Besant Nagar, Chennai, Tamil Nadu - 600090',
                'department'    => 'Fine Arts',
                'designation'   => 'Western & Classical Dance Instructor',
                'qualification' => 'Master of Performing Arts (Dance)',
                'joining_date'  => '2021-08-15',
                'basic_salary'  => 45000,
            ],
            [
                'employee_code' => 'EMP-180',
                'first_name'    => 'Raghavendra',
                'last_name'     => 'Rao',
                'gender'        => 'male',
                'dob'           => '1985-02-24',
                'mobile'        => '9840123495',
                'personal_email'=> 'raghav.rao85@gmail.com',
                'official_email'=> 'raghavendra.rao@schoolerp.in',
                'residential_address' => '16, Jayanagar 4th Block, Bangalore, Karnataka - 560011',
                'department'    => 'Science',
                'designation'   => 'PGT Physics & Astronomy',
                'qualification' => 'M.Sc. Theoretical Physics, B.Ed.',
                'joining_date'  => '2020-11-01',
                'basic_salary'  => 55000,
            ],
            [
                'employee_code' => 'EMP-181',
                'first_name'    => 'Smita',
                'last_name'     => 'Deshpande',
                'gender'        => 'female',
                'dob'           => '1994-05-11',
                'mobile'        => '9840123496',
                'personal_email'=> 'smita.desh94@gmail.com',
                'official_email'=> 'smita.deshpande@schoolerp.in',
                'residential_address' => '83, Aundh DP Road, Pune, Maharashtra - 411007',
                'department'    => 'Primary Education',
                'designation'   => 'PRT English & Phonics Specialist',
                'qualification' => 'M.A. English, Jolly Phonics Certified, B.Ed.',
                'joining_date'  => '2022-04-10',
                'basic_salary'  => 45000,
            ],
            [
                'employee_code' => 'EMP-182',
                'first_name'    => 'Vivek',
                'last_name'     => 'Mahajan',
                'gender'        => 'male',
                'dob'           => '1992-08-30',
                'mobile'        => '9840123497',
                'personal_email'=> 'vivek.mahajan92@gmail.com',
                'official_email'=> 'vivek.mahajan@schoolerp.in',
                'residential_address' => '27, Sector 18, Chandigarh - 160018',
                'department'    => 'Mathematics',
                'designation'   => 'TGT Mathematics & Vedic Maths',
                'qualification' => 'M.Sc. Mathematics, B.Ed.',
                'joining_date'  => '2022-09-01',
                'basic_salary'  => 48000,
            ],
            [
                'employee_code' => 'EMP-183',
                'first_name'    => 'Preeti',
                'last_name'     => 'Chauhan',
                'gender'        => 'female',
                'dob'           => '1990-03-05',
                'mobile'        => '9840123498',
                'personal_email'=> 'preeti.chauhan90@gmail.com',
                'official_email'=> 'preeti.chauhan@schoolerp.in',
                'residential_address' => '58, Rajpur Road, Dehradun, Uttarakhand - 248001',
                'department'    => 'Science',
                'designation'   => 'PGT Biotechnology & Genetics',
                'qualification' => 'M.Sc. Biotechnology, B.Ed.',
                'joining_date'  => '2021-01-20',
                'basic_salary'  => 54000,
            ],
            [
                'employee_code' => 'EMP-184',
                'first_name'    => 'Tarun',
                'last_name'     => 'Singhania',
                'gender'        => 'male',
                'dob'           => '1986-07-16',
                'mobile'        => '9840123499',
                'personal_email'=> 'tarun.singhania86@gmail.com',
                'official_email'=> 'tarun.singhania@schoolerp.in',
                'residential_address' => '120, Malviya Nagar, Jaipur, Rajasthan - 302017',
                'department'    => 'Commerce',
                'designation'   => 'Commerce & Financial Markets Faculty',
                'qualification' => 'M.Com, NCFM Certified, B.Ed.',
                'joining_date'  => '2020-03-15',
                'basic_salary'  => 56000,
            ],
            [
                'employee_code' => 'EMP-185',
                'first_name'    => 'Yamuna',
                'last_name'     => 'Sundararajan',
                'gender'        => 'female',
                'dob'           => '1989-12-28',
                'mobile'        => '9840123500',
                'personal_email'=> 'yamuna.sundar89@gmail.com',
                'official_email'=> 'yamuna.sundararajan@schoolerp.in',
                'residential_address' => '47, Anna Nagar East, Chennai, Tamil Nadu - 600102',
                'department'    => 'Primary Education',
                'designation'   => 'Special Education & Remedial Teaching',
                'qualification' => 'M.Sc. Psychology, B.Ed. Special Education',
                'joining_date'  => '2021-06-25',
                'basic_salary'  => 51000,
            ],
        ];

        foreach ($teachingStaff as $staff) {
            Employee::updateOrCreate(
                ['employee_code' => $staff['employee_code']],
                array_merge($staff, [
                    'employee_type' => 'teaching',
                    'nationality'   => 'Indian',
                    'category'      => 'general',
                    'is_active'     => true,
                    'salary_on_hold'=> false,
                    'tax_regime'    => 'new',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ])
            );
        }
    }
}
