<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employeesData = [
            // ── 1. TEACHING STAFF (12) ───────────────────────────
            [
                'employee_code' => 'EMP-101',
                'first_name'    => 'Rajesh',
                'last_name'     => 'Sharma',
                'employee_type' => 'teaching',
                'designation'   => 'Mathematics HOD',
                'department'    => 'Mathematics',
                'mobile'        => '9876543210',
                'official_email'=> 'rajesh.sharma@schoolerp.in',
                'qualification' => 'M.Sc. Mathematics, B.Ed.',
                'basic_salary'  => 55000,
                'joining_date'  => '2019-06-01',
                'gender'        => 'male',
            ],
            [
                'employee_code' => 'EMP-102',
                'first_name'    => 'Sunita',
                'last_name'     => 'Verma',
                'employee_type' => 'teaching',
                'designation'   => 'Senior Physics Teacher',
                'department'    => 'Science',
                'mobile'        => '9876543211',
                'official_email'=> 'sunita.verma@schoolerp.in',
                'qualification' => 'M.Sc. Physics, M.Ed.',
                'basic_salary'  => 52000,
                'joining_date'  => '2020-04-15',
                'gender'        => 'female',
            ],
            [
                'employee_code' => 'EMP-103',
                'first_name'    => 'Anil',
                'last_name'     => 'Kumar',
                'employee_type' => 'teaching',
                'designation'   => 'English Lecturer',
                'department'    => 'English',
                'mobile'        => '9876543212',
                'official_email'=> 'anil.kumar@schoolerp.in',
                'qualification' => 'M.A. English Literature, B.Ed.',
                'basic_salary'  => 48000,
                'joining_date'  => '2021-07-10',
                'gender'        => 'male',
            ],
            [
                'employee_code' => 'EMP-104',
                'first_name'    => 'Priya',
                'last_name'     => 'Nair',
                'employee_type' => 'teaching',
                'designation'   => 'Computer Science Teacher',
                'department'    => 'Computer Science',
                'mobile'        => '9876543213',
                'official_email'=> 'priya.nair@schoolerp.in',
                'qualification' => 'M.C.A., B.Tech',
                'basic_salary'  => 50000,
                'joining_date'  => '2021-08-01',
                'gender'        => 'female',
            ],
            [
                'employee_code' => 'EMP-105',
                'first_name'    => 'Vikram',
                'last_name'     => 'Singh',
                'employee_type' => 'teaching',
                'designation'   => 'Chemistry Teacher',
                'department'    => 'Science',
                'mobile'        => '9876543214',
                'official_email'=> 'vikram.singh@schoolerp.in',
                'qualification' => 'M.Sc. Chemistry, B.Ed.',
                'basic_salary'  => 46000,
                'joining_date'  => '2022-01-15',
                'gender'        => 'male',
            ],
            [
                'employee_code' => 'EMP-106',
                'first_name'    => 'Meenakshi',
                'last_name'     => 'Joshi',
                'employee_type' => 'teaching',
                'designation'   => 'Hindi Senior Teacher',
                'department'    => 'Languages',
                'mobile'        => '9876543215',
                'official_email'=> 'meenakshi.j@schoolerp.in',
                'qualification' => 'M.A. Hindi, B.Ed.',
                'basic_salary'  => 44000,
                'joining_date'  => '2020-11-01',
                'gender'        => 'female',
            ],
            [
                'employee_code' => 'EMP-107',
                'first_name'    => 'Suresh',
                'last_name'     => 'Rao',
                'employee_type' => 'teaching',
                'designation'   => 'Social Studies Teacher',
                'department'    => 'Social Sciences',
                'mobile'        => '9876543216',
                'official_email'=> 'suresh.rao@schoolerp.in',
                'qualification' => 'M.A. History, B.Ed.',
                'basic_salary'  => 45000,
                'joining_date'  => '2022-03-20',
                'gender'        => 'male',
            ],
            [
                'employee_code' => 'EMP-108',
                'first_name'    => 'Kavita',
                'last_name'     => 'Deshmukh',
                'employee_type' => 'teaching',
                'designation'   => 'Biology Teacher',
                'department'    => 'Science',
                'mobile'        => '9876543217',
                'official_email'=> 'kavita.d@schoolerp.in',
                'qualification' => 'M.Sc. Zoology, B.Ed.',
                'basic_salary'  => 47000,
                'joining_date'  => '2021-09-05',
                'gender'        => 'female',
            ],
            [
                'employee_code' => 'EMP-109',
                'first_name'    => 'Amit',
                'last_name'     => 'Gupta',
                'employee_type' => 'teaching',
                'designation'   => 'Physical Education Instructor',
                'department'    => 'Sports',
                'mobile'        => '9876543218',
                'official_email'=> 'amit.gupta@schoolerp.in',
                'qualification' => 'M.P.Ed.',
                'basic_salary'  => 42000,
                'joining_date'  => '2020-02-10',
                'gender'        => 'male',
            ],
            [
                'employee_code' => 'EMP-110',
                'first_name'    => 'Pooja',
                'last_name'     => 'Saxena',
                'employee_type' => 'teaching',
                'designation'   => 'Art & Craft Teacher',
                'department'    => 'Fine Arts',
                'mobile'        => '9876543219',
                'official_email'=> 'pooja.s@schoolerp.in',
                'qualification' => 'B.F.A. Fine Arts',
                'basic_salary'  => 40000,
                'joining_date'  => '2022-06-01',
                'gender'        => 'female',
            ],
            [
                'employee_code' => 'EMP-111',
                'first_name'    => 'Rohan',
                'last_name'     => 'Kulkarni',
                'employee_type' => 'teaching',
                'designation'   => 'Music Teacher',
                'department'    => 'Performing Arts',
                'mobile'        => '9876543220',
                'official_email'=> 'rohan.k@schoolerp.in',
                'qualification' => 'Sangeet Visharad',
                'basic_salary'  => 38000,
                'joining_date'  => '2023-01-10',
                'gender'        => 'male',
            ],
            [
                'employee_code' => 'EMP-112',
                'first_name'    => 'Deepa',
                'last_name'     => 'Menon',
                'employee_type' => 'teaching',
                'designation'   => 'Primary Teacher (Class 2)',
                'department'    => 'Primary Section',
                'mobile'        => '9876543221',
                'official_email'=> 'deepa.m@schoolerp.in',
                'qualification' => 'B.A., D.El.Ed.',
                'basic_salary'  => 39000,
                'joining_date'  => '2023-04-01',
                'gender'        => 'female',
            ],

            // ── 2. NON-TEACHING STAFF (8) ─────────────────────────
            [
                'employee_code' => 'EMP-113',
                'first_name'    => 'Ramesh',
                'last_name'     => 'Patel',
                'employee_type' => 'non_teaching',
                'designation'   => 'Chief Accountant',
                'department'    => 'Accounts & Finance',
                'mobile'        => '9876543222',
                'official_email'=> 'ramesh.patel@schoolerp.in',
                'qualification' => 'M.Com, Tally Certified',
                'basic_salary'  => 50000,
                'joining_date'  => '2018-05-10',
                'gender'        => 'male',
            ],
            [
                'employee_code' => 'EMP-114',
                'first_name'    => 'Anjali',
                'last_name'     => 'Mehta',
                'employee_type' => 'non_teaching',
                'designation'   => 'Head Librarian',
                'department'    => 'Library',
                'mobile'        => '9876543223',
                'official_email'=> 'anjali.m@schoolerp.in',
                'qualification' => 'M.Lib.Sc.',
                'basic_salary'  => 45000,
                'joining_date'  => '2019-10-01',
                'gender'        => 'female',
            ],
            [
                'employee_code' => 'EMP-115',
                'first_name'    => 'Alok',
                'last_name'     => 'Tiwari',
                'employee_type' => 'non_teaching',
                'designation'   => 'IT Administrator',
                'department'    => 'IT & Infrastructure',
                'mobile'        => '9876543224',
                'official_email'=> 'alok.t@schoolerp.in',
                'qualification' => 'B.Tech IT, CCNA',
                'basic_salary'  => 48000,
                'joining_date'  => '2021-02-15',
                'gender'        => 'male',
            ],
            [
                'employee_code' => 'EMP-116',
                'first_name'    => 'Neha',
                'last_name'     => 'Bhatia',
                'employee_type' => 'non_teaching',
                'designation'   => 'Front Desk Receptionist',
                'department'    => 'Administration',
                'mobile'        => '9876543225',
                'official_email'=> 'neha.b@schoolerp.in',
                'qualification' => 'B.B.A.',
                'basic_salary'  => 32000,
                'joining_date'  => '2022-08-01',
                'gender'        => 'female',
            ],
            [
                'employee_code' => 'EMP-117',
                'first_name'    => 'Manoj',
                'last_name'     => 'Pandey',
                'employee_type' => 'non_teaching',
                'designation'   => 'Store Manager',
                'department'    => 'Inventory & Stores',
                'mobile'        => '9876543226',
                'official_email'=> 'manoj.p@schoolerp.in',
                'qualification' => 'B.Com',
                'basic_salary'  => 35000,
                'joining_date'  => '2020-09-10',
                'gender'        => 'male',
            ],
            [
                'employee_code' => 'EMP-118',
                'first_name'    => 'Smita',
                'last_name'     => 'Chavan',
                'employee_type' => 'non_teaching',
                'designation'   => 'HR Executive',
                'department'    => 'Human Resources',
                'mobile'        => '9876543227',
                'official_email'=> 'smita.c@schoolerp.in',
                'qualification' => 'MBA HR',
                'basic_salary'  => 42000,
                'joining_date'  => '2022-04-12',
                'gender'        => 'female',
            ],
            [
                'employee_code' => 'EMP-119',
                'first_name'    => 'Ganesh',
                'last_name'     => 'Shinde',
                'employee_type' => 'non_teaching',
                'designation'   => 'Science Lab Assistant',
                'department'    => 'Science Laboratories',
                'mobile'        => '9876543228',
                'official_email'=> 'ganesh.s@schoolerp.in',
                'qualification' => 'B.Sc. Chemistry',
                'basic_salary'  => 30000,
                'joining_date'  => '2023-02-01',
                'gender'        => 'male',
            ],
            [
                'employee_code' => 'EMP-120',
                'first_name'    => 'Shalini',
                'last_name'     => 'Dube',
                'employee_type' => 'non_teaching',
                'designation'   => 'Office Assistant',
                'department'    => 'Administration',
                'mobile'        => '9876543229',
                'official_email'=> 'shalini.d@schoolerp.in',
                'qualification' => 'B.A.',
                'basic_salary'  => 28000,
                'joining_date'  => '2023-05-15',
                'gender'        => 'female',
            ],

            // ── 3. DRIVERS (6) ────────────────────────────────────
            [
                'employee_code'     => 'EMP-121',
                'first_name'        => 'Gurdeep',
                'last_name'         => 'Singh',
                'employee_type'     => 'driver',
                'designation'       => 'School Bus Driver (Route 1)',
                'department'        => 'Transport',
                'mobile'            => '9876543230',
                'official_email'    => 'gurdeep.driver@schoolerp.in',
                'license_number'    => 'DL-042019881234',
                'license_expiry'    => '2028-11-30',
                'assigned_vehicle'  => 'Bus No. MH-12-AB-1001 (52 Seater)',
                'qualification'     => '10th Pass, Heavy Commercial License',
                'basic_salary'      => 28000,
                'joining_date'      => '2019-03-01',
                'gender'            => 'male',
            ],
            [
                'employee_code'     => 'EMP-122',
                'first_name'        => 'Ramakant',
                'last_name'         => 'Yadav',
                'employee_type'     => 'driver',
                'designation'       => 'School Bus Driver (Route 2)',
                'department'        => 'Transport',
                'mobile'            => '9876543231',
                'official_email'    => 'ramakant.y@schoolerp.in',
                'license_number'    => 'DL-122018774567',
                'license_expiry'    => '2027-08-15',
                'assigned_vehicle'  => 'Bus No. MH-12-AB-1002 (40 Seater)',
                'qualification'     => '10th Pass, HMV License',
                'basic_salary'      => 27000,
                'joining_date'      => '2020-08-10',
                'gender'            => 'male',
            ],
            [
                'employee_code'     => 'EMP-123',
                'first_name'        => 'Balwinder',
                'last_name'         => 'Gill',
                'employee_type'     => 'driver',
                'designation'       => 'School Bus Driver (Route 3)',
                'department'        => 'Transport',
                'mobile'            => '9876543232',
                'official_email'    => 'balwinder.g@schoolerp.in',
                'license_number'    => 'DL-092020993322',
                'license_expiry'    => '2029-01-20',
                'assigned_vehicle'  => 'Bus No. MH-12-AB-1003 (52 Seater)',
                'qualification'     => '12th Pass, Heavy Driving Badge',
                'basic_salary'      => 29000,
                'joining_date'      => '2021-04-01',
                'gender'            => 'male',
            ],
            [
                'employee_code'     => 'EMP-124',
                'first_name'        => 'Shivaji',
                'last_name'         => 'Kadam',
                'employee_type'     => 'driver',
                'designation'       => 'Staff Van Driver',
                'department'        => 'Transport',
                'mobile'            => '9876543233',
                'official_email'    => 'shivaji.k@schoolerp.in',
                'license_number'    => 'DL-142017665544',
                'license_expiry'    => '2026-12-10',
                'assigned_vehicle'  => 'Winger Van MH-12-CD-505',
                'qualification'     => '10th Pass, LMV & Commercial License',
                'basic_salary'      => 25000,
                'joining_date'      => '2022-02-15',
                'gender'            => 'male',
            ],
            [
                'employee_code'     => 'EMP-125',
                'first_name'        => 'Mohammed',
                'last_name'         => 'Rafi',
                'employee_type'     => 'driver',
                'designation'       => 'School Bus Driver (Route 4)',
                'department'        => 'Transport',
                'mobile'            => '9876543234',
                'official_email'    => 'm.rafi@schoolerp.in',
                'license_number'    => 'DL-112019448877',
                'license_expiry'    => '2028-05-30',
                'assigned_vehicle'  => 'Bus No. MH-12-AB-1004 (40 Seater)',
                'qualification'     => '10th Pass, Heavy Commercial License',
                'basic_salary'      => 27500,
                'joining_date'      => '2021-11-01',
                'gender'            => 'male',
            ],
            [
                'employee_code'     => 'EMP-126',
                'first_name'        => 'Pradeep',
                'last_name'         => 'Rathod',
                'employee_type'     => 'driver',
                'designation'       => 'Emergency Ambulance Driver',
                'department'        => 'Transport / Medical',
                'mobile'            => '9876543235',
                'official_email'    => 'pradeep.r@schoolerp.in',
                'license_number'    => 'DL-082021556677',
                'license_expiry'    => '2030-03-15',
                'assigned_vehicle'  => 'Ambulance MH-12-EM-999',
                'qualification'     => '12th Pass, First Aid Certified',
                'basic_salary'      => 26000,
                'joining_date'      => '2023-01-05',
                'gender'            => 'male',
            ],

            // ── 4. CLEANERS (5) ───────────────────────────────────
            [
                'employee_code'     => 'EMP-127',
                'first_name'        => 'Shanti',
                'last_name'         => 'Devi',
                'employee_type'     => 'cleaner',
                'designation'       => 'Senior Housekeeping Supervisor',
                'department'        => 'Sanitation & Hygiene',
                'mobile'            => '9876543236',
                'assigned_block'    => 'Main Administrative Building',
                'shift_timing'      => 'Morning Shift (7:00 AM - 3:30 PM)',
                'basic_salary'      => 20000,
                'joining_date'      => '2019-07-01',
                'gender'            => 'female',
            ],
            [
                'employee_code'     => 'EMP-128',
                'first_name'        => 'Ramdas',
                'last_name'         => 'Pawra',
                'employee_type'     => 'cleaner',
                'designation'       => 'Floor Cleaner (Block A)',
                'department'        => 'Sanitation & Hygiene',
                'mobile'            => '9876543237',
                'assigned_block'    => 'Academic Block A (Classes 1 to 5)',
                'shift_timing'      => 'Morning Shift (7:00 AM - 3:30 PM)',
                'basic_salary'      => 18000,
                'joining_date'      => '2021-05-10',
                'gender'            => 'male',
            ],
            [
                'employee_code'     => 'EMP-129',
                'first_name'        => 'Sunil',
                'last_name'         => 'Solanki',
                'employee_type'     => 'cleaner',
                'designation'       => 'Floor Cleaner (Block B)',
                'department'        => 'Sanitation & Hygiene',
                'mobile'            => '9876543238',
                'assigned_block'    => 'Secondary Block B (Classes 6 to 10)',
                'shift_timing'      => 'Morning Shift (7:00 AM - 3:30 PM)',
                'basic_salary'      => 18000,
                'joining_date'      => '2022-03-01',
                'gender'            => 'male',
            ],
            [
                'employee_code'     => 'EMP-130',
                'first_name'        => 'Kalavati',
                'last_name'         => 'Bhoi',
                'employee_type'     => 'cleaner',
                'designation'       => 'Sanitation Staff (Girls Section)',
                'department'        => 'Sanitation & Hygiene',
                'mobile'            => '9876543239',
                'assigned_block'    => 'Girls Washrooms & Common Areas',
                'shift_timing'      => 'Full Day Shift (7:30 AM - 4:00 PM)',
                'basic_salary'      => 18500,
                'joining_date'      => '2020-09-15',
                'gender'            => 'female',
            ],
            [
                'employee_code'     => 'EMP-131',
                'first_name'        => 'Subhash',
                'last_name'         => 'Chavan',
                'employee_type'     => 'cleaner',
                'designation'       => 'Grounds & Campus Cleaner',
                'department'        => 'Sanitation & Hygiene',
                'mobile'            => '9876543240',
                'assigned_block'    => 'Sports Playground & Outer Campus',
                'shift_timing'      => 'Early Shift (6:30 AM - 3:00 PM)',
                'basic_salary'      => 17500,
                'joining_date'      => '2023-02-10',
                'gender'            => 'male',
            ],

            // ── 5. NANNIES / NAANIS (4) ───────────────────────────
            [
                'employee_code'     => 'EMP-132',
                'first_name'        => 'Laxmi',
                'last_name'         => 'Kamble',
                'employee_type'     => 'nanny',
                'designation'       => 'Kindergarten Senior Naani',
                'department'        => 'Pre-Primary Caretaker',
                'mobile'            => '9876543241',
                'assigned_block'    => 'Nursery & LKG Section',
                'shift_timing'      => 'School Hours (8:00 AM - 2:30 PM)',
                'qualification'     => 'Child Caretaker Training Certificate',
                'basic_salary'      => 19500,
                'joining_date'      => '2019-01-15',
                'gender'            => 'female',
            ],
            [
                'employee_code'     => 'EMP-133',
                'first_name'        => 'Savitri',
                'last_name'         => 'Gaikan',
                'employee_type'     => 'nanny',
                'designation'       => 'UKG Section Caretaker Naani',
                'department'        => 'Pre-Primary Caretaker',
                'mobile'            => '9876543242',
                'assigned_block'    => 'UKG & Playgroup Rooms',
                'shift_timing'      => 'School Hours (8:00 AM - 2:30 PM)',
                'qualification'     => 'Child Handling & Safety Certified',
                'basic_salary'      => 19000,
                'joining_date'      => '2020-10-01',
                'gender'            => 'female',
            ],
            [
                'employee_code'     => 'EMP-134',
                'first_name'        => 'Parvati',
                'last_name'         => 'Shelke',
                'employee_type'     => 'nanny',
                'designation'       => 'Primary School Helper Naani',
                'department'        => 'Primary Caretaker',
                'mobile'            => '9876543243',
                'assigned_block'    => 'Primary Block (Classes 1 & 2)',
                'shift_timing'      => 'Full School Shift (7:45 AM - 3:15 PM)',
                'qualification'     => 'First Aid & Child Safety Certified',
                'basic_salary'      => 18500,
                'joining_date'      => '2021-08-15',
                'gender'            => 'female',
            ],
            [
                'employee_code'     => 'EMP-135',
                'first_name'        => 'Manjula',
                'last_name'         => 'Bhosale',
                'employee_type'     => 'nanny',
                'designation'       => 'Daycare & Activity Room Naani',
                'department'        => 'Daycare & Creche',
                'mobile'            => '9876543244',
                'assigned_block'    => 'Daycare Center & Activity Hall',
                'shift_timing'      => 'Extended Shift (8:30 AM - 5:00 PM)',
                'qualification'     => 'Infant & Toddler Care Specialist',
                'basic_salary'      => 20000,
                'joining_date'      => '2022-06-10',
                'gender'            => 'female',
            ],
        ];

        foreach ($employeesData as $empData) {
            Employee::updateOrCreate(
                ['employee_code' => $empData['employee_code']],
                array_merge($empData, ['is_active' => true])
            );
        }
    }
}
