<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Expense;
use App\Models\AcademicYear;
use App\Models\User;

class ExpenseSeeder extends Seeder
{
    public function run(): void
    {
        $currentYear = AcademicYear::current() ?? AcademicYear::first();
        $admin = User::first();
        $adminId = $admin?->id ?? 1;

        $academicItems = [
            [
                'expense_number'       => 'EXP-ACAD-20260810-101',
                'category'             => 'academic',
                'subcategory'          => 'books_learning_materials',
                'title'                => 'NCERT & Oxford Curriculum Textbooks Bundle (Classes VI-X)',
                'description'          => 'Procurement of revised 2026 curriculum textbooks and workbooks for senior school library and student reference desk.',
                'amount'               => 84500.00,
                'expense_date'         => '2026-08-10',
                'payment_method'       => 'Bank Transfer (NEFT)',
                'vendor_name'          => 'Saraswati Book Depot & Educational Publishers',
                'vendor_invoice_no'    => 'SBD-2026-8819',
                'approval_status'      => 'approved',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-08-11 11:30:00',
                'approved_by'          => $adminId,
                'approved_at'          => '2026-08-12 15:00:00',
            ],
            [
                'expense_number'       => 'EXP-ACAD-20260814-102',
                'category'             => 'academic',
                'subcategory'          => 'lab_consumables',
                'title'                => 'Physics & Chemistry Lab Reagents and Borosilicate Glassware',
                'description'          => 'Fresh chemical supplies including titration indicators, acids, salts, pipettes, and test tubes for CBSE senior board practicals.',
                'amount'               => 42000.00,
                'expense_date'         => '2026-08-14',
                'payment_method'       => 'Cheque',
                'vendor_name'          => 'Apex Scientific & Lab Instruments Pvt Ltd',
                'vendor_invoice_no'    => 'APX-7741',
                'approval_status'      => 'approved',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-08-15 10:00:00',
                'approved_by'          => $adminId,
                'approved_at'          => '2026-08-16 14:20:00',
            ],
            [
                'expense_number'       => 'EXP-ACAD-20260822-103',
                'category'             => 'academic',
                'subcategory'          => 'exam_stationary',
                'title'                => 'Mid-Term Examination Security Envelopes & Answer Booklets (5,000 Units)',
                'description'          => 'Barcoded 16-page ruled answer sheets, graph papers, and tamper-proof confidential seal bags for Mid-Term Exams.',
                'amount'               => 28500.00,
                'expense_date'         => '2026-08-22',
                'payment_method'       => 'Bank Transfer (IMPS)',
                'vendor_name'          => 'National Security Printing & Stationery Works',
                'vendor_invoice_no'    => 'NSP-9012',
                'approval_status'      => 'verified',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-08-23 09:45:00',
                'approved_by'          => null,
                'approved_at'          => null,
            ],
            [
                'expense_number'       => 'EXP-ACAD-20260828-104',
                'category'             => 'academic',
                'subcategory'          => 'sports_equipment',
                'title'                => 'District Athletics Meet Kits, Footballs, Badminton Racquets & Medals',
                'description'          => 'Sports kits replenishment including Nivia footballs, Yonex badminton sets, shot puts, relay batons, and podium trophies.',
                'amount'               => 36000.00,
                'expense_date'         => '2026-08-28',
                'payment_method'       => 'UPI',
                'vendor_name'          => 'Champion Sports & Athletic Supplies',
                'vendor_invoice_no'    => 'CMP-5120',
                'approval_status'      => 'approved',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-08-29 16:15:00',
                'approved_by'          => $adminId,
                'approved_at'          => '2026-08-30 11:10:00',
            ],
            [
                'expense_number'       => 'EXP-ACAD-20260901-105',
                'category'             => 'academic',
                'subcategory'          => 'student_events',
                'title'                => 'Annual Cultural Fest Stage Backdrop, Sound System & Lighting Rental',
                'description'          => '3-day auditorium sound system, LED wall display, and dynamic stage spot lights for Annual Talents Exhibition.',
                'amount'               => 95000.00,
                'expense_date'         => '2026-09-01',
                'payment_method'       => 'Bank Transfer (NEFT)',
                'vendor_name'          => 'Royal Stage Decor & Audio Visuals',
                'vendor_invoice_no'    => 'RSD-3341',
                'approval_status'      => 'approved',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-09-02 12:00:00',
                'approved_by'          => $adminId,
                'approved_at'          => '2026-09-03 10:30:00',
            ],
            [
                'expense_number'       => 'EXP-ACAD-20260904-106',
                'category'             => 'academic',
                'subcategory'          => 'workshops_training',
                'title'                => 'NEP 2020 Experiential Pedagogy Faculty Workshop Honorarium',
                'description'          => '2-day in-service faculty development seminar conducted by certified CBSE master trainers for 45 teachers.',
                'amount'               => 18000.00,
                'expense_date'         => '2026-09-04',
                'payment_method'       => 'Cheque',
                'vendor_name'          => 'Centre for Pedagogical Excellence',
                'vendor_invoice_no'    => 'CPE-4410',
                'approval_status'      => 'pending',
                'verified_by'          => null,
                'verified_at'          => null,
                'approved_by'          => null,
                'approved_at'          => null,
            ],
            [
                'expense_number'       => 'EXP-ACAD-20260906-107',
                'category'             => 'academic',
                'subcategory'          => 'software_licenses',
                'title'                => 'Interactive Smart Board Curriculum Software Annual Multi-Classroom License',
                'description'          => 'Digital learning software suite renewal for 12 smart classrooms with 3D science simulations and maths tools.',
                'amount'               => 54000.00,
                'expense_date'         => '2026-09-06',
                'payment_method'       => 'Corporate Credit Card',
                'vendor_name'          => 'EduTech Global Learning Systems',
                'vendor_invoice_no'    => 'ETG-9801',
                'approval_status'      => 'approved',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-09-07 14:00:00',
                'approved_by'          => $adminId,
                'approved_at'          => '2026-09-08 09:30:00',
            ],
            [
                'expense_number'       => 'EXP-ACAD-20260907-108',
                'category'             => 'academic',
                'subcategory'          => 'other_academic',
                'title'                => 'National Science Olympiad Enrollment Kits & Study Material Packs',
                'description'          => 'Registration forms and past papers compilation for 120 participating students across Grades IV to IX.',
                'amount'               => 15000.00,
                'expense_date'         => '2026-09-07',
                'payment_method'       => 'UPI',
                'vendor_name'          => 'Science Olympiad Foundation Partner Desk',
                'vendor_invoice_no'    => 'SOF-2026-112',
                'approval_status'      => 'rejected',
                'rejection_reason'     => 'Olympiad registration fees must be collected directly from registered parents, not funded from institutional core reserve.',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-09-07 16:30:00',
                'approved_by'          => $adminId,
                'approved_at'          => '2026-09-08 11:00:00',
            ],
        ];

        $maintenanceItems = [
            [
                'expense_number'       => 'EXP-MAINT-20260805-201',
                'category'             => 'maintenance',
                'subcategory'          => 'building_repairs_civil',
                'title'                => 'Main Academic Block Terrace Waterproofing & Exterior Acrylic Coating',
                'description'          => 'Pre-monsoon polymer waterproofing membrane application and elastomeric exterior weather-proof coating over 4,500 sq ft.',
                'amount'               => 145000.00,
                'expense_date'         => '2026-08-05',
                'payment_method'       => 'Bank Transfer (RTGS)',
                'vendor_name'          => 'Shree Balaji Waterproofing & Civil Contractors',
                'vendor_invoice_no'    => 'SBW-1049',
                'approval_status'      => 'approved',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-08-06 10:15:00',
                'approved_by'          => $adminId,
                'approved_at'          => '2026-08-07 14:00:00',
            ],
            [
                'expense_number'       => 'EXP-MAINT-20260812-202',
                'category'             => 'maintenance',
                'subcategory'          => 'electrical_power',
                'title'                => 'Diesel Generator (62.5 KVA) Annual Servicing & Diesel Refill (500L)',
                'description'          => 'Engine oil change, air filter replacement, alternator brush check, and 500 liters of bulk diesel for uninterrupted campus backup.',
                'amount'               => 48000.00,
                'expense_date'         => '2026-08-12',
                'payment_method'       => 'Cheque',
                'vendor_name'          => 'Kirloskar Power Systems & Fuel Station',
                'vendor_invoice_no'    => 'KPS-8840',
                'approval_status'      => 'approved',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-08-13 11:00:00',
                'approved_by'          => $adminId,
                'approved_at'          => '2026-08-14 17:20:00',
            ],
            [
                'expense_number'       => 'EXP-MAINT-20260819-203',
                'category'             => 'maintenance',
                'subcategory'          => 'plumbing_water',
                'title'                => 'Campus Central Commercial RO Drinking Water Membrane Overhaul',
                'description'          => 'Replacement of 4 high-pressure Dow Filmtec reverse osmosis membranes, UV quartz tubes, and water quality testing certification.',
                'amount'               => 32500.00,
                'expense_date'         => '2026-08-19',
                'payment_method'       => 'Bank Transfer (NEFT)',
                'vendor_name'          => 'PureAqua Industrial Solutions',
                'vendor_invoice_no'    => 'PAI-6211',
                'approval_status'      => 'approved',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-08-20 15:45:00',
                'approved_by'          => $adminId,
                'approved_at'          => '2026-08-21 16:30:00',
            ],
            [
                'expense_number'       => 'EXP-MAINT-20260825-204',
                'category'             => 'maintenance',
                'subcategory'          => 'bus_fleet_repairs',
                'title'                => 'School Bus Fleet (Bus #04 & #07) Brake Shoes, Tie Rod & RTO Fitness Prep',
                'description'          => 'Complete braking system overhaul, suspension greasing, speed-governor calibration, and RTO fitness compliance check.',
                'amount'               => 68000.00,
                'expense_date'         => '2026-08-25',
                'payment_method'       => 'Bank Transfer (NEFT)',
                'vendor_name'          => 'Tata Commercial Motors & Fleet Services',
                'vendor_invoice_no'    => 'TCM-9081',
                'approval_status'      => 'approved',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-08-26 12:30:00',
                'approved_by'          => $adminId,
                'approved_at'          => '2026-08-27 10:00:00',
            ],
            [
                'expense_number'       => 'EXP-MAINT-20260830-205',
                'category'             => 'maintenance',
                'subcategory'          => 'security_cctv',
                'title'                => 'Campus Surveillance Upgrade: 8 HD IP Cameras & 16-Channel NVR',
                'description'          => 'Installation of 8 infrared outdoor bullet cameras covering school playground, main gate, and bus bay parking area.',
                'amount'               => 58000.00,
                'expense_date'         => '2026-08-30',
                'payment_method'       => 'Cheque',
                'vendor_name'          => 'Hikvision VisionTech Security Systems',
                'vendor_invoice_no'    => 'VTS-4412',
                'approval_status'      => 'verified',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-08-31 16:00:00',
                'approved_by'          => null,
                'approved_at'          => null,
            ],
            [
                'expense_number'       => 'EXP-MAINT-20260902-206',
                'category'             => 'maintenance',
                'subcategory'          => 'furniture_fixtures',
                'title'                => 'Classroom Dual Desks & Ergonomic Faculty Chair Carpentry Repairs',
                'description'          => 'Welding, teakwood ply replacement, and edge-banding for 65 student dual-desks in junior wing.',
                'amount'               => 26000.00,
                'expense_date'         => '2026-09-02',
                'payment_method'       => 'Cash',
                'vendor_name'          => 'Vishwakarma Modular Carpentry Works',
                'vendor_invoice_no'    => 'VMC-318',
                'approval_status'      => 'approved',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-09-03 14:10:00',
                'approved_by'          => $adminId,
                'approved_at'          => '2026-09-04 11:30:00',
            ],
            [
                'expense_number'       => 'EXP-MAINT-20260905-207',
                'category'             => 'maintenance',
                'subcategory'          => 'electrical_power',
                'title'                => 'Main Substation 4-Pole Structure Earth-Pit Re-boring & Chemical Compound',
                'description'          => 'Boring of 3 fresh chemical earthing pits with copper-bonded rods to ensure campus electrical surge protection.',
                'amount'               => 38500.00,
                'expense_date'         => '2026-09-05',
                'payment_method'       => 'Bank Transfer (IMPS)',
                'vendor_name'          => 'Suraksha Earthing & Electrical Engineers',
                'vendor_invoice_no'    => 'SEE-719',
                'approval_status'      => 'pending',
                'verified_by'          => null,
                'verified_at'          => null,
                'approved_by'          => null,
                'approved_at'          => null,
            ],
            [
                'expense_number'       => 'EXP-MAINT-20260908-208',
                'category'             => 'maintenance',
                'subcategory'          => 'campus_sanitation',
                'title'                => 'Bulk Hospital-Grade Disinfectants, Detergents & Floor Buffing Pads',
                'description'          => 'Quarterly supply of organic toilet cleaners, micro-fiber mops, floor deodorizers, and hygiene dispensers.',
                'amount'               => 22500.00,
                'expense_date'         => '2026-09-08',
                'payment_method'       => 'UPI',
                'vendor_name'          => 'CleanPro Hygiene Solutions Ltd',
                'vendor_invoice_no'    => 'CPH-1190',
                'approval_status'      => 'approved',
                'verified_by'          => $adminId,
                'verified_at'          => '2026-09-08 17:00:00',
                'approved_by'          => $adminId,
                'approved_at'          => '2026-09-09 09:15:00',
            ],
        ];

        foreach (array_merge($academicItems, $maintenanceItems) as $item) {
            $item['academic_year_id'] = $currentYear?->id;
            $item['created_by']       = $adminId;
            Expense::updateOrCreate(
                ['expense_number' => $item['expense_number']],
                $item
            );
        }
    }
}
